"""Smoke tests for the generated CPACS website."""

from __future__ import annotations

import unittest
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urlsplit

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "output"
IGNORED_SCHEMES = {"data", "javascript", "mailto", "tel"}
COPIED_HTML_TREES = {"documentation"}
HOST_LIKE_LINKS = {"cpacs.de", "www.cpacs.de"}


class LinkCollector(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.links: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attributes = dict(attrs)
        for name in ("href", "src"):
            value = attributes.get(name)
            if value:
                self.links.append(value.strip())


def generated_html_files() -> list[Path]:
    files = []
    for path in OUTPUT.rglob("*.html"):
        relative = path.relative_to(OUTPUT)
        if relative.parts and relative.parts[0] in COPIED_HTML_TREES:
            continue
        files.append(path)
    return sorted(files)


def local_candidates(source: Path, raw_link: str) -> list[Path]:
    """Return locally checkable targets for a link.

    Fully qualified HTTP(S) links are intentionally not checked here. Even links
    to cpacs.de can refer to legacy material that is not generated by the current
    checkout. Network link checking belongs in a separate, non-blocking job.

    Historical CPACS content also uses paths such as ``images/foo.png`` as if
    they were relative to the site root. Such links appear in generated author
    and category pages below subdirectories. Therefore both the HTML-file-relative
    and site-root-relative interpretations are accepted.
    """

    link = raw_link.strip()
    if not link or link.startswith("#") or link.startswith("//"):
        return []

    lower_link = link.lower().rstrip("/")
    if lower_link in HOST_LIKE_LINKS:
        # Historical malformed web link such as href="www.cpacs.de".
        # It is not a local filesystem reference.
        return []

    parsed = urlsplit(link)
    scheme = parsed.scheme.lower()

    if scheme in IGNORED_SCHEMES:
        return []
    if scheme in {"http", "https"} or parsed.netloc:
        return []
    if scheme:
        # Unknown schemes are not local file references.
        return []

    path_text = unquote(parsed.path)
    if not path_text:
        return []

    if path_text.startswith("/"):
        raw_candidates = [OUTPUT / path_text.lstrip("/")]
    else:
        raw_candidates = [source.parent / path_text, OUTPUT / path_text]

    candidates: list[Path] = []
    for candidate in raw_candidates:
        if path_text.endswith("/"):
            candidate /= "index.html"
        resolved = candidate.resolve()
        if resolved not in candidates:
            candidates.append(resolved)
    return candidates


def candidate_exists(candidate: Path) -> bool:
    if candidate.is_dir():
        candidate = candidate / "index.html"
    return candidate.exists()


class GeneratedSiteTests(unittest.TestCase):
    def test_expected_entry_points_exist(self) -> None:
        expected = (
            "index.html",
            "CNAME",
            "pages/get-cpacs.html",
            "pages/documentation.html",
        )
        for relative in expected:
            with self.subTest(path=relative):
                self.assertTrue((OUTPUT / relative).is_file(), relative)

    def test_custom_domain_is_preserved(self) -> None:
        self.assertEqual((OUTPUT / "CNAME").read_text(encoding="utf-8").strip(), "www.cpacs.de")

    def test_schema_archive_is_present(self) -> None:
        schema_root = OUTPUT / "schema"
        self.assertTrue(schema_root.is_dir(), "addContent/schema was not copied")
        self.assertTrue(any(schema_root.rglob("*.xsd")), "No XSD schema was copied")

    def test_generated_html_contains_no_build_placeholders_or_local_paths(self) -> None:
        forbidden = ("{filename}", "{static}", "file://", "d:\\rce\\plugins")
        for path in generated_html_files():
            text = path.read_text(encoding="utf-8", errors="replace").lower()
            with self.subTest(path=path.relative_to(OUTPUT)):
                for marker in forbidden:
                    self.assertNotIn(marker, text)

    def test_local_relative_links_resolve(self) -> None:
        broken: list[str] = []
        output_root = OUTPUT.resolve()

        for source in generated_html_files():
            parser = LinkCollector()
            parser.feed(source.read_text(encoding="utf-8", errors="replace"))

            for link in parser.links:
                candidates = local_candidates(source, link)
                if not candidates:
                    continue

                in_output = []
                for candidate in candidates:
                    try:
                        candidate.relative_to(output_root)
                    except ValueError:
                        continue
                    in_output.append(candidate)

                if not in_output:
                    broken.append(f"{source.relative_to(OUTPUT)} -> {link} (outside output)")
                    continue

                if not any(candidate_exists(candidate) for candidate in in_output):
                    broken.append(f"{source.relative_to(OUTPUT)} -> {link}")

        self.assertFalse(broken, "Broken local relative links:\n" + "\n".join(sorted(set(broken))))


if __name__ == "__main__":
    unittest.main()
